# Generated by Django 4.2.1 on 2023-05-07 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_merchant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACCEPT', 'Accept'), ('PENDING', 'Pending'), ('REJECT', 'Reject')], default='PENDING', max_length=200)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='shop.shop')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='shop.shop')),
            ],
        ),
    ]
