# Generated by Django 4.2.1 on 2023-05-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shopconnector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopconnector',
            name='status',
            field=models.CharField(choices=[('ACCEPT', 'Accept'), ('PENDING', 'Pending'), ('REJECT', 'Reject')], default='', max_length=200),
        ),
    ]
