# Generated by Django 4.2.1 on 2023-05-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_shopconnector_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
