# Generated by Django 4.2.1 on 2023-05-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_product_merchant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
